### ISSUE TITLE
configuration and query

### ISSUE THREAD

**Issue by TadjM** [Matt-Dionis/gatsby-source-googlemaps-geocoding#2]
Hello I followed the steps to configure the plugin  but the new query "allLocationData" is not  available in GraphQL i dont know if i missed something during configuration.  Thanks
The steps followed: https://www.gatsbyjs.org/packages/gatsby-source-googlemaps-geocoding/

**Comment by Matt-Dionis** [comment]
@TadjM I'd love to help but will need a bit more info. Would you mind sharing what you see in GraphiQL when you click **Docs** in the upper right then **Query**? You should see a list of fields which are queryable including `allLocationData`.

**Comment by TadjM** [comment]
That’s the problem when I open DOCS I don’t see AllLocationData. I was using YARN now I tried using NPM AND ITS WORKING. I guess the problem is with yarn. 

Best regards
Tadjoudine Mouhamed

**Comment by MattDionis** [comment]
Glad it's working for you now! Closing this out.
